### ISSUE TITLE
scalarisctl checkinstallation fails on AArch64, Fedora 33 

### ISSUE THREAD

**Issue by LutzWeischerFujitsu** [scalaris-team/scalaris#103]
(base) [jw@cn05 scalaris]$ scalarisctl checkinstallation
Running cleanup...
Running basic tests...ATTENTION
WARNING: the hostnames reported by Erlang and the OS do not match.
erlang (get_erlang_hostname):
     -> cn05.cluster.local
system (get_sys_hostname):
     -> cn05
 If debugging does not work, try one of the following solutions:
 - during start, specify a full node name using IPs with '-n node@<IP>'
 - set environment variable ERLANG_HOSTNAME to your IP
 - during start, specify a full node name using the erlang hostname with '-n node@cn05.cluster.local'
 - set environment variable ERLANG_HOSTNAME to the erlang hostname
 - fix your hostname setup system-wide
 Please refer to your system's manual to set your hostname, e.g. change the
 values in /etc/hosts or /etc/hostname, and check that it is consistent with
 the DNS.
Continuing basic tests...ATTENTION
INFO: could not find Scalaris' Java-API files.
You won't be able to use the 'scalaris' command line script to access Scalaris.
  'make java' will build the Java-API
We were trying to run: /usr/local/bin/scalaris -h
Continuing basic tests...ATTENTION

WARNING: unable to start the erlang_js application
 You won't be able to use JavaScript Map-Reduce jobs
We were trying to run: /usr/bin/erl -noinput -sasl sasl_error_logger false -boot start_sasl -eval "ok = application:start(erlang_js), {ok, JS} = js_driver:new(), ok = js:define(JS, <<"var addOne = function(a){ return a + 1; }">>), {ok,4} = js:call(JS, <<"addOne">>, [3]), halt(0)."
Continuing basic tests...DONE
Running Scalaris run-time tests...
  NOTE: yaws port not specified (you can specify it using -y <port> for /usr/local/bin/scalarisctl).
        Python, Python3, Ruby, C++ API tests may fail if the port is different in
        one of the config files.
  Starting Scalaris FAILED
  (result: {badrpc,nodedown}
=ERROR REPORT==== 22-Mar-2021::15:34:52.400511 ===
** System running to use fully qualified hostnames **
** Hostname cn05 is illegal **).
  we were trying to run: /usr/local/bin/scalarisctl -t first -m -d start
(base) [jw@cn05 scalaris]$

**Comment by tschuett** [comment]
The error message comes from here: https://github.com/scalaris-team/scalaris/blob/069f65d3ad9f28f1e4be84ef3658ea30b70eb550/bin/scalarisctl.in#L314

The OS hostname is checked here:
https://github.com/scalaris-team/scalaris/blob/069f65d3ad9f28f1e4be84ef3658ea30b70eb550/bin/scalarisctl.in#L162

The Erlang check is here:
https://github.com/scalaris-team/scalaris/blob/069f65d3ad9f28f1e4be84ef3658ea30b70eb550/bin/scalarisctl.in#L154

The odd thing is that
`hostname -f`
does not include the domain name.

The corresponding Erlang expression is `node()`.

**Comment by schintke** [comment]
In other words: scalarisctl checkinstallation looks whether itself and the machine are well configured. Here, it complains that the machine should be set up to deliver a fully qualified hostname when 'hostname -f' is executed at the top of the output you provided.
You should consider fixing that aspect on your machine (setting host and domainname so that 'hostname -f' delivers the fully qualified hostname). There is nothing wrong with scalarisctl checkinstallation here.

**Comment by tschuett** [comment]
For scalaris to work correctly, Erlang and the host OS must agree on the hostname. Checkinstallation revealed that they differ. According to hostname's man page:
` -f    Include domain information in the printed name.` This is not the case in your setup. Our output hints at checking  /etc/hosts or /etc/hostname.
