### ISSUE TITLE
Using Range Read with JSON RPC

### ISSUE THREAD

**Issue by abronan** [scalaris-team/scalaris#81]
I came back very recently on implementing a Go client to Scalaris (https://github.com/abronan/go-scalaris). I can successfully read / write / delete / addOnNumber / compareAndSwap.

One last thing though is how to do a **Range Read** of keys?

I see that you need to give a *begin* and *end* **hashed** keys but there is no way to get the hashed version of the key using Json RPC. Also I couldn't find an example on how to do this with the Ruby/Java and Python API.

I guess that this is possible but how can we use Range Reads other than using the Erlang client?

I would be happy to contribute on the doc once I get this part right and if it's possible :+1:

**Comment by schintke** [comment]
What do you expect from the range read? Clients usually do not benefit from that, as the delivered data are potentially outdated and are not consistent. The range read operates below the replication layer. So, depending on the given range you only access one replica or get entries duplicated from several replicas. The range read is used internally and is not intended for the API at the upper levels. For the Go API, support for the Scalaris transactions (see api_tx) would be more interesting.

**Comment by abronan** [comment]
@schintke Thanks! This was my misunderstanding then. I thought that the Range Read would act as a Tree/Subtree kind of command to help you create a structure. Somehow like Zookeeper with a parent and child keys so you can scan all your child keys but yes, I get it now.

I wanted to get all the keys under a given `prefix` for example.

I'm better of storing everything under a single key and create a structure inside that key am I right?

**Comment by schintke** [comment]
There are various possibilities how to express higher level structures using a flat key-value store when you have transactional changes available, as in Scalaris. Having a large structured value in a single key is one of them. Depending on your performance and latency requirements the solutions may be more or less appropriate for your use case. We studied some of them in our experiments when we mapped a subset of the Wikipedia relational database schema to Scalaris. For further technical details you may consult our publication 'Nico Kruber, Florian Schintke, Michael Berlin. A Relational Database Schema on the Transactional Key-Value Store Scalaris. Proceedings of 2nd Workshop on Scalable Cloud Data Management, 2014.'http://dx.doi.org/10.1109/BigData.2014.7004441

**Comment by abronan** [comment]
Thanks for your answers and pointers. I went through the abstract and it seems to be exactly what I need.
