### ISSUE TITLE
Cluster setup using docker containers

### ISSUE THREAD

**Issue by mindnuts** [scalaris-team/scalaris#82]
Hi..do you plan to create a simple guide on how to run scalaris cluster using docker containers on the cloud? I tried to follow the user guide but the scalaris nodes fail to see each other when running inside a docker container.

Cheers

**Comment by tschuett** [comment]
Hi,

- could you please run 'scalarisctl checkinstallation' in your container.
- have you checked that the necessary [ports](http://scalaris.zib.de/faq.html#which-ports-are-used-by-scalaris) are open?

Thanks.

**Comment by mindnuts** [comment]
@tschuett Can you please tell me what ports should be opened on the first node, second node etc. In my testing i opened 14195 on the first node along with 8000. On other nodes i just opened 8000.

Also, it would be super good if there is a FAQ section which talks about getting scalaris to work in a clustered OS, for example CoreOS. I like scalaris and really want to use it on my production setup.

**Comment by tschuett** [comment]
Port 8000 is not enough on the second node. 8000 is only for the web interface. You need to open 14195 on all nodes. All internal communication goes over 14195.
